node_lines:
- node_line_name: prompt_node_line
  nodes:
    - node_type: prompt_maker
      strategy:
        metrics:
          - metric_name: kice_metric
      modules:
        - module_type: fstring
          prompt:
          - |            
            국어 시험 문제를 푸는 대한민국의 똑똑한 고3 수험생으로서 위의 요약을 바탕으로 다음 문제의 답을 구하세요.
            지문을 읽고, 질문에 대한 답을 1부터 5까지의 선택지 중에 한 개만 골라서 대답해야 합니다.
            
            지문 :
            {retrieved_contents}
            
            질문 :
            {query}
            
            문제를 풀이할 때, 반드시 지문을 참고하세요. 문제는 무조건 1개의 정답만 있습니다. 문제를 풀이할 때 모든 선택지들을 검토하세요.
            먼저 문제를 이해하고, 문제 해결을 위하여 계획을 세워보세요.
            그 다음, 문제를 해결하기 위해 그 계획에 따라 단계별로 실행하세요.

            다음의 형식을 따라 답변하세요.
            1번: (선택지 1번에 대한 답변) + "(지문 속 근거가 된 문장)"
            2번: (선택지 2번에 대한 답변) + "(지문 속 근거가 된 문장)"
            3번: (선택지 3번에 대한 답변) + "(지문 속 근거가 된 문장)"
            4번: (선택지 4번에 대한 답변) + "(지문 속 근거가 된 문장)"
            5번: (선택지 5번에 대한 답변) + "(지문 속 근거가 된 문장)"
            최종 정답: (최종 정답)
            
            정답 :
    - node_type: generator
      strategy:
        metrics:
          - metric_name: kice_metric
      modules:
        - module_type: openai_llm
          llm: [gpt-4o-mini, gpt-3.5-turbo, gpt-4o]
          batch: 3
